version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DB_PATH=/app/data/market_data.db
      - MODEL_DIR=/app/models
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: oasis_db
      POSTGRES_USER: oasis_user
      POSTGRES_PASSWORD: oasis_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: